project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.Rmd"             # Exclude .Rmd files, but try to avoid them for consistency
    - "!_scripts/*.qmd"    # Exclude utility scripts
    - "!_drafts/*.qmd"     # Exclude draft content
    - "!admin/*.qmd"       # Exclude admin content
    - "!sandpit/*.qmd"     # Exclude sandpit content
    #- "syllabus/index.qmd:pdf" # Add specific PDF outputs
  resources:
    - files/*.Rmd
    - files/*.html
    
# Global execute options
execute:
  freeze: auto
  cache: false
  
website:
  title: "TSB"
  favicon: "img/tsb_hex.png"
  navbar:
    left:
      - syllabus/index.qmd
      - lectures/index.qmd
      - resources.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/rich-ramsey/tsb
  back-to-top-navigation: false
  page-footer: "The Social Brain"
    
  sidebar:
    - id: "main-sidebar"  # Default sidebar for most pages
      style: "floating"
      logo: "img/tsb_hex.png" 
      search: true
          
    - id: "lectures-sidebar"  # Special sidebar for lecture pages
      style: "floating"
      logo: "img/tsb_hex.png" 
      search: true
      contents:
        - section: "<b>Lectures</b>"
          href: lectures/index.qmd
          contents:
            - text: "<mark>Intro</mark>"
            -  lectures/01_intro.qmd
            - text: "<mark>Crisis and reform</mark>"
            -  lectures/02_crisis.qmd
            -  lectures/03_reform.qmd
            -  lectures/04_theory.qmd
            -  lectures/05_reflection.qmd
            - text: "<mark>Social neuroscience</mark>"
            -  lectures/06_neuro_1.qmd
            -  lectures/07_neuro_2.qmd
            -  lectures/08_neuro_3.qmd
            - text: "<mark>Neurodiversity</mark>"
            -  lectures/09_neurodiversity.qmd
            -  lectures/10_clinic.qmd
            -  lectures/11_loneliness.qmd
            -  lectures/12_autism.qmd
            -  lectures/13_attention.qmd
            - text: "<mark>Essay writing</mark>"
            -  lectures/14_essay.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor_options: 
  type: source
  chunk_output_type: console
  markdown: 
    wrap: 72
    references:
      location: block
    canonical: true
  chunk: 
    tidy: true
    wrap: 80

