---
title: "The Social Brain: Critical Perspectives on Science, Society and Neurodiversity"
sidebar: main-sidebar
---

## Welcome

This is the course website for *The Social Brain: Critical Perspectives on Science, Society and Neurodiversity*, developed and taught by [Dr. Rich Ramsey](https://rich-ramsey.com/) at ETH Zürich. 

## Course description

Meaningful social interactions form the foundation of cohesive societies, with implications extending far beyond psychology and neuroscience into education, technology, policy, and healthcare.
Although the scientific study of social behavior has only recently emerged as a distinct research discipline, its applications are already widespread, raising critical questions about the relationship between knowledge creation and societal applications.
Simultaneously, multiple scientific disciplines are confronting a "replication crisis," revealing challenges in reproducing findings and highlighting questionable research practices that demand critical reflection on how scientific knowledge is produced and communicated.
This seminar examines the historical, moral, epistemological, and societal contexts of social neuroscience research, encouraging students to question established frameworks and consider a variety of new perspectives.
We begin by exploring how a widespread replication crisis has emerged in science and what it means for both research practices and public science literacy.
The seminar then applies this critical lens to social neuroscience, examining how reconceptualizing cognitive variation as a natural continuum rather than through deficit models can transform scientific understanding and promote more inclusive societal perspectives that value the rich diversity of human experience and capability.

## Website information

On this website, you can find the course [syllabus](syllabus/syllabus.html), as well as the details for the course [lectures](lectures/index.html). 

## Acknowledgments

The structure of this website closely follows open access materials shared by:

-   Maureen Ritchey. [*Programming for Psychology and Neuroscience*](https://ritcheym.github.io/ppn/). 
