---
title: "Reflection"
---

## Objectives

This week, I would like you to reflect on the extent to which the reproducibility crisis extends beyond psychology and human neuroscience.
Most of you have varied backgrounds, which span computer science, physics, chemistry, biology, maths etc.
Therefore, I would like you to situate what you have learnt in the last 3
 weeks within a broader context of scientific research more generally. 

See below for more details of the assignment.

## Discussion material

It is your task to go away and find relevant papers to discuss and include in your reflective writing piece.

To get you thinking outside of psychology and neuroscience, here are some recent reports in the journal Nature about untrustworthy medical research:

[link 1](https://www.nature.com/articles/d41586-023-02299-w)

[link 2](https://www.nature.com/articles/d41586-024-04206-3)

[link 3](https://www.science.org/doi/10.1126/science.adk9181)

## Assignment 

There is an assignment this week, which is **NOT** marked.
I repeat, it is **not marked**, but it is compulsory to hand it in via email by ***Monday October 5th at 9am***.
Please write between 500 and 750 words on the extent to which the reproducibility crisis extends beyond psychology and human neuroscience.

## Lecture 

Please also bring your written assignment to class.
Each of you will first share your reflections with your neighbour (or with a small group) and then read each other's assignments.
This process will serve to kick-start discussions about the extent to which issues with reproducibility are more widespread than the domains of psychology and human neuroscience.